### ISSUE TITLE
can't install on miui13(android12)

### ISSUE THREAD

**Issue by 493505110** [wacko1805/MagiskGapps#17]
![Screenshot_2022-10-29-09-21-59-351_bin mt plus](https://user-images.githubusercontent.com/29498336/198755579-4ea4d2d3-0b44-4ced-8f7a-463941bf6642.jpg)
![Screenshot_2022-10-29-09-22-28-952_com topjohnwu magisk](https://user-images.githubusercontent.com/29498336/198755580-83316f74-ee53-438e-bd61-a023d137dec1.jpg)

Device: `Redmi Note 11 5G`

**Comment by 330377782** [comment]
+1

**Comment by xiaoning356** [comment]
me,too

**Comment by Nelocompne** [comment]
"unzip error"
The contents of the compressed package are damaged. Please repair the damaged files and repack them.

Corrupt file found:
`MagiskGApps-a.12.v.0.1.core.zip`
![图片](https://user-images.githubusercontent.com/40271506/223363532-85268b22-c973-4c2d-af75-d4f2147fea07.png)

**Comment by wacko1805** [comment]
Fixed in v8.3.23. Update now uploading for all versions. 

https://magiskgapps.com/download.html?version=android-12-ALPHA
