### ISSUE TITLE
The Module doesn't seem to work :/

### ISSUE THREAD

**Issue by Cloufish** [wacko1805/MagiskGapps#2]
I install it from source (`.zip`), through MagiskManager:
![image](https://user-images.githubusercontent.com/32965886/129548175-1144d01a-89a5-447e-8eb7-d0b555211281.png)
![image](https://user-images.githubusercontent.com/32965886/129548230-2711e322-0cc9-4bed-b164-9065c19d4e8d.png)
Even though installation succeeds, after reboot there're no GApps installed
![image](https://user-images.githubusercontent.com/32965886/129548362-a182879f-b19a-453d-95f5-4714b4d34c37.png)

Magisk is installed on AVD, with Android 10 and API Level 29.

I'd be pleased to provide more information, e.g. via logcat, please provide instructions for that

**Comment by wacko1805** [comment]
Hello, MagiskGApps is for Android 11 (r) only, as seen in the second screenshot. MagiskGApps will also not work on x86 devices.
