### ISSUE TITLE
How to prevent family link loop forever?

### ISSUE THREAD

**Issue by darkautism** [wacko1805/MagiskGapps#20]
It seems family link will not work?

**Comment by wacko1805** [comment]
Hello, from my own testing, Family Link is working fine. Can I please have some details:
Android Version,
Device, 
MagiskGApps version.
Thanks!

**Comment by darkautism** [comment]
Hi wacko,

Thanks for reply. I found why family link loop forever and resolve it.
But i forget to close issue.
