### ISSUE TITLE
Not working with universal sagetynet fix.

### ISSUE THREAD

**Issue by axydavid** [wacko1805/MagiskGapps#22]
When I install universal safetynet fix the google services constantly crash. How can I use bank apps if I can't use safetynetfix?

**Comment by wacko1805** [comment]
Are you able to supply any logs?

**Comment by runoono** [comment]
@axydavid are you using magisk's deny list? that caused a lot of problems for me
@wacko1805 when I add com.android.gms etc I get a bunch of "Failed to open APK '/system/priv-app/...': I/O error" logs but it all goes away when I lift the deny list? either way, I pass YASNAC with safety net fix and your gapps module

**Comment by wacko1805** [comment]
Closed as this relates to old MagiskGApps varients.
