### ISSUE TITLE
Add TV Package

### ISSUE THREAD

**Issue by dedsecproyt** [wacko1805/MagiskGapps#28]
I need TV Package (PlayStore, AndroidTV Launcher, Android TV Customization, Android TV Widget, TV Voice Input, Remote Control Service, Second Screen Setup, Second Screen Setup Auth) for create mini TV-Box from OrangePI 5 Plus

I think it will be a very good addition to your project because anyone can do it TV-Box which he wants, not a large tablet with unadapted programs for the TV

**Comment by wacko1805** [comment]
If this is still in need, please recommend some commonly used TVGapps and i could implement a script in the future
