### ISSUE TITLE
SourceForge and website downloads don't work

### ISSUE THREAD

**Issue by yu-rei** [wacko1805/MagiskGapps#29]

**Comment by yu-rei** [comment]
SF download just never starts no matter what browser I use and the website doesn't have downloads on it

![image](https://github.com/wacko1805/MagiskGapps/assets/94387506/43ac0cbe-a99f-4916-8ef2-b77ba1c4ec9d)

**Comment by wacko1805** [comment]
Thanks for letting me know, a fix is on the way. in the meantime, please use the sourceforge link in the readme or the link below:

https://sourceforge.net/projects/magiskgapps/files/

**Comment by wacko1805** [comment]
Old MG is not maintained. Please use MagiskGApps.com or the readme for more info.
