### ISSUE TITLE
Is TVstock or TVmini support possible? 

### ISSUE THREAD

**Issue by Quackdoc** [wacko1805/MagiskGapps#4]
I was wondering if it would be possible to add tv support for this it would be really cool, and although niche, useful in it's own right

**Comment by wacko1805** [comment]
Hey, thanks for the suggestion. I will definitely include TVStock and TVMini in the next update.

**Comment by leohearts** [comment]
You can alternatively just install an xml file which defines tv feature : https://android.googlesource.com/device/google/atv/+/master/permissions/tv_core_hardware.xml
then install play store of TV version from ApkMirror,  and Google apps will update to it's TV version automatically. This works for me.

**Comment by Quackdoc** [comment]
> You can alternatively just install an xml file which defines tv feature :

what does that involve? just coping to system/etc/permissions and adding root ownership?

**Comment by leohearts** [comment]
> 

yes

**Comment by Quackdoc** [comment]
Thanks, it's not without flaws, I can't use home button anymore, need to figure out away around that, and figuring out how to get settings to work, but this is a large step, thanks mate.

**Comment by wacko1805** [comment]
Unfortunately, i have not gotten TV Gapps to work, and i do not have a device to test it on properly, so MagiskGApps tv GApps will not be getting released
