### ISSUE TITLE
Google Play Services and Android Setup keep crashing.

### ISSUE THREAD

**Issue by GoedendagMC** [wacko1805/MagiskGapps#7]
I installed this on an Android 11 CAOS rom (arm64 A/B). If I install the vanilla variant (bvz), we get both errors as seen in title, when installing the goapps (boz) variant, I only get the Android Setup crash message. I cannot install the full gapps (bgz), because my partition doesn't have enough space. When I look this up online, most people advise a factory reset, which would be a great idea, except for the fact that doing that also removes this module. Please help.

**Comment by wacko1805** [comment]
Hey could you please give me the logs?

**Comment by NightHammer1000** [comment]
Had the same Issue.
Had to disable zygisk

**Comment by Luciogi** [comment]
I faced gsm crashes while zygisk was enabled.
For me Enabling "Enforce DenyList" fixes crashed

**Comment by Skorpion96** [comment]
i just tried the module in leOS gsi, i have the same issue, tried various versions without success

**Comment by wacko1805** [comment]
> i just tried the module in leOS gsi, i have the same issue, tried various versions without success

What android version was the leOS gsi based off?

**Comment by Skorpion96** [comment]
It was android 12 and 13, I asked in leos group and they told me that Google services can't work on leos

**Comment by wacko1805** [comment]
> It was android 12 and 13, I asked in leos group and they told me that Google services can't work on leos

Ok, as this is not an issue with MG, i am closing this issue
